### ISSUE TITLE
Decide what License we are going to use.

### ISSUE THREAD

**Issue by selfup** [pindell-matt/fe_bucket#15]
No description needed here!

**Comment by cite-reader** [comment]
Just dropping my 2¢.

My favorite license overall is [Apache 2](https://www.apache.org/licenses/LICENSE-2.0.txt), since I can use Apache 2-licensed things anywhere I care about them and it has that nifty patent-rights assignment clause in it.

Rust things are usually dual-licensed under Apache 2 and [MIT](https://opensource.org/licenses/MIT) licenses at the recipient's option, following the example of `rustc` and the standard libraries. The stated rationale for this is that the Apache 2 license is incompatible with the GPL v2, but the MIT license _is_ compatible, and mostly equivalent less patent assignment. I don't really care about GPL2, but you might.

I'd like to -1 the GPL or AGPL as being overly-convoluted and inappropriate for library use. The GPL v2 is incompatible with the GPL v3, for example, which has caused problems for the Linux kernel in the past. It's not clear that the rights the AGPL asserts are even granted by copyright law, either. The LGPL is probably functional.

**Comment by selfup** [comment]
If Rust things are usually dual-licensed, I would be more than happy to follow suit with having both the Apache 2 and the MIT license.

This makes sense, as people have the freedom to choose whichever route they please.
